### ISSUE TITLE
BUG: Error when looking at technical paper

### ISSUE THREAD

**Issue by ErieMeyer** [RTICWDT/college-scorecard#1115]
![screen shot 2015-09-06 at 4 53 46 pm](https://cloud.githubusercontent.com/assets/1626026/9706603/ef566e44-54b7-11e5-98f1-985f41a5d3c9.png)

4:53, chrome, mac

To recreate:

- Go to data page on staging
- Click "download technical paper"
- See this error

**Comment by brownpl** [comment]
I think this was perhaps a federalist link issue - seems to be fine on the production site.
