### ISSUE TITLE
scale up Cloud Foundry instances for production API

### ISSUE THREAD

**Issue by ultrasaurus** [RTICWDT/college-scorecard#1131]

**Comment by ultrasaurus** [comment]
@ozzyjohnson I've never actually done this before.  I know this can be in the ```manifest.yml``` but I'd like to have multiple instances on production and just one in the other environments.  What's the best way to accomplish that?

**Comment by ozzyjohnson** [comment]
@ultrasaurus - The number of instances to launch can be configured in manifest with the [instances](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#instances) key or post-launch with `cf scale -i N` where N is the number of instances to create.

    ---
      ...
      instances: 2

**Comment by ultrasaurus** [comment]
@ozzyjohnson how do people generally have a different manifest for different environments?  right now it is checked into github, so the same file is deployed on dev, staging and production.

**Comment by LisaGee** [comment]
@dnesting Can you help track on this too? Thanks

**Comment by ozzyjohnson** [comment]
@ultrasaurus - I suggest using multiple manifests and choosing between them
with `-f` at push time. The downside here is manging multiple files and the
limitations of Travis CI and possibly others which can only do a plain `cf
push` per branch.

A few projects are using [multi-app](
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-apps)
manifests and specifying the app name to choose which to deploy. This would
give you fewer files to manage with the downside of potentially pushing
multiple apps if someone does a `cf push` without an app name.

Most everyone ends up with some kind of wrapper script as the general
consensus has been that advanced manifest features like inheritance aren't
worth the trouble.

**Comment by ultrasaurus** [comment]
next steps to change ​`instances: 1`​ and then write a script that does a push and cf scale, depending on environment

**Comment by brownpl** [comment]
These are setup! Yas!
