### ISSUE TITLE
S3 access and logging

### ISSUE THREAD

**Issue by diego-** [RTICWDT/college-scorecard#1249]
teach folks how to access s3 logs

**Comment by diego-** [comment]
opened devops ticket to provision accounts for: Erie, Lisa, Holly

**Comment by ozzyjohnson** [comment]
Created. 

@ErieMeyer @LisaGee @hollyallen - Ping me for next steps or give me an email / slack id where I can send a self-destructing password link.

**Comment by hollyallen** [comment]
I have my login now.

**Comment by barkimedes** [comment]
@hollyallen I have no idea what to do next with this issue. Thoughts?

**Comment by hollyallen** [comment]
I'd want to verify that @LisaGee has access as well, and you should get access too. Otherwise this can be closed.

**Comment by brownpl** [comment]
Seems this issue is now closed.
