### ISSUE TITLE
Text change for search by ZIP

### ISSUE THREAD

**Issue by claremccann** [RTICWDT/college-scorecard#1250]
Currently, if you search by ZIP, the distance box says "no limit," but searching pulls up only schools within that ZIP. Instead, it should say something like "0 miles" to indicate that you need to enter a distance or only schools in the ZIP will be pulled up.

**Comment by brittag** [comment]
Interestingly I ran into this issue too, on my first try of the site. I was curious to look up the "score" of a specific university, so I typed in the zipcode for the area near that university. I got zero results, so I wondered if something was broken. Then I changed my query to put in that zipcode with a limit of 20 miles, which got the results I wanted.

I agree with changing this to say "0 miles", or possibly changing it to have a reasonable default limit with text saying "x miles" reflecting that default.

**Comment by barkimedes** [comment]
Should also pay attention to #979 if you work on this issue.

**Comment by kynetiv** [comment]
Fixed in #1551.
