### ISSUE TITLE
Create Social Media Promo Image

### ISSUE THREAD

**Issue by jjoteal** [RTICWDT/college-scorecard#1279]
Need image for promotional purposes on social media

![image](https://cloud.githubusercontent.com/assets/12192706/9831800/f3853124-5932-11e5-927a-a4db99bc72a7.png)

**Comment by meiqimichelle** [comment]
@jjoteal I fixed the missing link so that the image that we have now will show up (once we push to production again). Right now it is the background happy people photo. Do you want to make a unique one for shares?

**Comment by jjoteal** [comment]
Let's go with the happy people image for shares as well, as it really is the only image we have on the site.

**Comment by brownpl** [comment]
Share image should be updated to be a scaled down version of the current site background.
