### ISSUE TITLE
We should make sure our data set is listed on the front page of api.data.gov

### ISSUE THREAD

**Issue by LisaGee** [RTICWDT/college-scorecard#1298]
https://api.data.gov/

Currently lists:
Web Service Documentation
Explore our available Web services.

Census
Federal Communications Commission
Food and Drug Administration
General Services Administration
National Institutes of Health
National Renewable Energy Laboratory
Regulations.gov API
U.S. Department of Agriculture

**Comment by ErieMeyer** [comment]
cc @gbinal

**Comment by dnesting** [comment]
cc @mbellotti

**Comment by mbellotti** [comment]
More it this point, if USDS apis are listed on Data.gov we should be including information about where to find the most up-to-date documentation for them. Happy to take this on if we know the current contact person for Data.gov.

**Comment by ErieMeyer** [comment]
cc @gbinal

**Comment by brownpl** [comment]
Currently displayed underneath Department of Ed and seems to be inline with everyone else.
