### ISSUE TITLE
Bottom pagination doesn't scroll to top of refreshed list

### ISSUE THREAD

**Issue by krogsgard** [RTICWDT/college-scorecard#1303]
When paginating archives of returned data, the bottom pagination doesn't auto-scroll to the top of the list, which makes for an awkward user experience, especially on mobile where scroll is more difficult. It'd be nice if paginated pushed the viewport back up to the top of the list.

**Comment by mark-adams** [comment]
#1290 fixes this

**Comment by brownpl** [comment]
Looks resolved to me! Huzzah!
