### ISSUE TITLE
Right-size to post-launch traffic levels.

### ISSUE THREAD

**Issue by ozzyjohnson** [RTICWDT/college-scorecard#1334]
Traffic levels are sure stabilize somewhere different than the launch surge. See the day/day week/week dashboard for reference.

https://rpm.newrelic.com/accounts/1065766/custom_dashboards/pages/7437

**Comment by hollyallen** [comment]
@ozzyjohnson do the traffic levels and infra size match now? I think we did this task.

**Comment by yozlet** [comment]
@sharms, can you and the Cloud.gov folks give us any input on what our various resource allocations should be for current traffic levels, vs what they actually are?

**Comment by abisker** [comment]
@yozlet and @sharms is this moot now since we expanded ES?

**Comment by brownpl** [comment]
Closing this, as we have since relaunched new instances and will follow previous scale patterns.
