### ISSUE TITLE
Tune Pingdom alerts

### ISSUE THREAD

**Issue by LisaGee** [RTICWDT/college-scorecard#1346]
different policy for production vs. Dev, for example

**Comment by LisaGee** [comment]
@ozzyjohnson Do you have any recollection about what this meant? Or recommendations on what we want to do here?

**Comment by ozzyjohnson** [comment]
This is about turning down the sensitivity of the alerts. At the current
setting, alerts are pushed the instant any check is missed which has
potential to alert on spurious things. Tuning them down should eliminate
false positives.

**Comment by brownpl** [comment]
Closing as we are no longer monitoring with pingdom.
