### ISSUE TITLE
Name search doesn't work if <3 alphanumeric characters at the beginning

### ISSUE THREAD

**Issue by claremccann** [RTICWDT/college-scorecard#1356]
Eg., St. John's College in Santa Fe. When I search on any variation of "St. John's College" or "St John's College" or "St Johns College" nothing comes up. When I go to New Mexico and ask for a list of colleges in that state, it does appear:
>https://collegescorecard.ed.gov/school/?245652-St-John-s-College<

The same problem seems to occur when searching for a sister campus in Annapolis Maryland.

![stjohns](https://cloud.githubusercontent.com/assets/13874735/10319177/e3b20f54-6c3a-11e5-847d-e2ded9f12d9d.jpg)

![stjohnsnope](https://cloud.githubusercontent.com/assets/13874735/10319191/f47770a4-6c3a-11e5-955a-3388eb01b184.jpg)

**Comment by ultrasaurus** [comment]
@LisaGee @barkimedes check this out:  https://federalist.18f.gov/preview/18F/college-choice/ex

You can search for "st louis" and get results... order is maybe not what people would expect.  Please test it and add notes about what you search for and the results you get vs. expect to get :)

**Comment by kynetiv** [comment]
This was implemented in the Open Data Maker [1.4.1 release](https://github.com/RTICWDT/open-data-maker/releases/tag/1.4.1)
