### ISSUE TITLE
As a user I want to search for school names which contain two letter words

### ISSUE THREAD

**Issue by hollyallen** [RTICWDT/college-scorecard#1370]
As a user I want to search for school names, like St Louis, which contain two letter words. Currently only searches for names with three letter words yield results.

Steps to reproduce:
1. On College Scorecard homepage, enter "St" in the Name search box

Expected Result:
* Search results with colleges with "St" in their names

Current Result:
* 0 search results

**Comment by hollyallen** [comment]
@LisaGee said she may also want to be able to search for a single character. @ultrasaurus is going to create a test site for @LisaGee to review so she can see if it has the behavior she likes.

**Comment by ultrasaurus** [comment]
@LisaGee @barkimedes check this out:  https://federalist.18f.gov/preview/18F/college-choice/ex

You can search for "st louis" and get results... order is maybe not what people would expect.  Please test it and add notes about what you search for and the results you get vs. expect to get :)

**Comment by LisaGee** [comment]
When I search for "a & m", I get 0 results, but there is at least Alabama A & M and Texas A & M in the data set.
https://federalist.18f.gov/preview/18F/college-choice/ex/school/?100654-Alabama-A-M-University

See #1356 & #1344.

I understand that this ticket only handles 2-letter words, but perhaps it makes sense to try to address all the name search issues at once so we can understand the effect they have as a whole?

**Comment by LisaGee** [comment]
One good test is to search for "St John": https://federalist.18f.gov/preview/18F/college-choice/ex/search/?name=St%20John&sort=advantage:desc

This search returns several unexpected results, like: Johnson State and John C Calhoun State Community College.

But doesn't return: Saint John's Seminary. Yet searching for "St John's" does. There is something off here.

**Comment by saintsoup52** [comment]
Many of these issues would be resolved by including school aliases from IPEDS, because this has been an issue on college navigator for years

http://nces.ed.gov/collegenavigator/?q=St+john&s=all&pg=2

**Comment by barkimedes** [comment]
@ultrasaurus seeing weird behavior, too. When I search for 

"fo": Contains 71 schools (seems to be most schools that have a word that start with fo)
"for": Contains ALL schools <== this is weird.
"ford": Contains only two schools (that start with ford)

@LisaGee Do you know: should we just be checking the beginnings of words or do we want to search anywhere in the name? For example, if I search for ford, should it also find Stanford?

**Comment by barkimedes** [comment]
We are going to take a little bit of time to step back and think a bit more about how this should work a little more holistically. And then we can better figure out what experiments to try next.

**Comment by barkimedes** [comment]
Per @LisaGee's suggestion, I think in a different issue, the idea was to just hardcode some schools and search terms. (For example, if someone types in St as a search term, we should add to the results any school that has St in the name).

So on that recommendation, I found 172 schools that have 1 or 2 letter words in the names (excludes "of" and "at"). So I'm just left wondering what is a good format to provide that to you guys and how we may integrate that into scorecard.

For example, would a dictionary of search term => [schools] work? e.g. 
{
  "St": ["St Matthew", "St Mark's", "St Luke", "St John's Seminary"],
  "de": ["El de Barge University"],
}

Or should I just give you a list of 1 and 2 letter words to search for as search terms?

@abisker Thoughts for how you guys may approach this in the code so we know how to give you the data for it?

**Comment by abisker** [comment]
Looping in @ultrasaurus for her thoughts on this approach.

**Comment by abisker** [comment]
@barkimedes is the hope to resolve #1356 with this?

**Comment by barkimedes** [comment]
@abisker Yes, I think ideally both issues would be solved.

I just wanted to note for context: I think this is an idea worth exploring. I made the update above to get the ball rolling and to give some idea of about how many schools we would need to include if we hard-coded them in. So assuming ~170 isn't an untenable amount and we were to go with some sort of hard-coded approach, what would be involved in making that happen and how much effort would it require?

**Comment by abisker** [comment]
Great, thanks for the clarification @barkimedes. So @ultrasaurus, just looking for thoughts on pros/cons of this approach and what it would entail to get a ballpark on the size of this and when we should tackle.

**Comment by kynetiv** [comment]
This was implemented in the Open Data Maker [1.4.1 release](https://github.com/RTICWDT/open-data-maker/releases/tag/1.4.1)
