### ISSUE TITLE
As a developer, I would like the API documentation to be clear about what is supported so that I know which features have been tested.

### ISSUE THREAD

**Issue by barkimedes** [RTICWDT/college-scorecard#1378]
Reported by @hollyallen. She can provide more details. But apparently the data tool doesn't do a great job of being clear about what data is supported via the api and what data isn't. Or things that should work but haven't been tested vs. things that we know will work. So we should make that more clear.

**Comment by hollyallen** [comment]
The api documentation currently lives here: https://github.com/18F/open-data-maker/blob/api-docs/API.md

It implies that all Field Parameters and Option Parameters defined in the data dictionary would work, but in fact they do not. 

Success Criteria:
* API Documentation at https://github.com/18F/open-data-maker/blob/api-docs/API.md lists the set of parameters that are expected to work.

**Comment by yozlet** [comment]
@hollyallen Do you by any chance remember which parameters don't work?

**Comment by yozlet** [comment]
Ah, it was this issue with the `location` field: https://github.com/18F/open-data-maker/issues/227

**Comment by abisker** [comment]
@yozlet following the trail to https://github.com/18F/open-data-maker/pull/283 is this resolved now?

**Comment by barkimedes** [comment]
FYI, I'm planning to close this issue on September 1, 2022. I haven't worked on this project in 6 years and I can't find a different way to get this issue off of my open issues list. If you still need the issue, I'd suggest someone who still works on College Scorecard opening a new issue and referencing this one.

@alexsmithRTI -- tagging you because you're the person I see has committed to this repo recently and I suspect you'll know if this would cause any problem.

Thanks!
