### ISSUE TITLE
Completion rate for less-than-four-year schools needs to use 150% (not 200%)

### ISSUE THREAD

**Issue by saintsoup52** [RTICWDT/college-scorecard#1379]
This is the exact opposite #956...

Not to revisit this issue again... but this decision has caused confusion among stakeholders and makes it difficult for VA to mirror the outcomes on the College Scorecard.

VA is publishing student veteran outcome measures... they only have graduation rates for 2 years school (150%NT).

Right now on the comparison tool... we choose to use the same rates you display on the Scorecard tool... but that is 200%NT for 2 year schools. Basically we are comparing apples to oranges now.

If we can revisit this... that would be great.

**Comment by barkimedes** [comment]
@claremccann @mitzcow My understanding is that this is a policy issue. How would you like to address it (assigned to Clare for research purposes). Thanks!

**Comment by kynetiv** [comment]
With the latest [data release](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.8.0), and per ED instruction, both 4yr and less-than-4yr completion rates use the 150% data. On the API side of things, in the Open Data Maker `data.yaml`,  the entry is calculated with `C150_L4_POOLED_SUPP or C150_4_POOLED_SUPP`. In a sense, this rolls back #956.
