### ISSUE TITLE
As the Department of Ed, I would like to encourage students to explore schools they may not have considered to date and might be a good fit, so they are exposed to enough information without being overwhelmed and can make a well-informed choice

### ISSUE THREAD

**Issue by barkimedes** [RTICWDT/college-scorecard#1401]

**Comment by LisaGee** [comment]
@barkimedes - How do we define "good fit"? That's what we struggled with in the initial version.

**Comment by barkimedes** [comment]
@LisaGee I dunno :us: But @jjoteal is going to try to gather data through usability tests and (now that I have access!) I'm starting to look at analytics to see what we can glean about current user behavior that could help inform this.

We have talked about this behavior a lot, but we didn't have a github issue to track it, so Jess and I created one.

**Comment by LisaGee** [comment]
Thanks. Also – Can you update the story to make the “why” a little more concrete? Why does a student want to “consider multiple schools”? What does that help them achieve?

**Comment by jjoteal** [comment]
Updated the story a bit -- feel free to edit!

**Comment by LisaGee** [comment]
So, is this the same as the original story we had: “If you’re interested in this school, you might also like….”? Where we had to figure out what the criteria was by which we would display other “similar” options?

**Comment by jjoteal** [comment]
It's different -- essentially, this is a research task aimed at trying to solve for "what is the best way we can broaden students horizons so that they consider more well-performing schools that they may have not considered to-date."  That *might* take the form of "suggested schools," the original "help me find schools that are best for me" widget, and/or some form of the comparison tool. The exact feature is TBD pending user interviews and usability testing (scheduled for late January). In other words, this story states the GOAL and not the solution.

**Comment by LisaGee** [comment]
Got it. That explanation sums it up perfectly. The “additional” was throwing me off. You mean “additional in life”, as opposed to “additional to the school I’ve already search for”. We’re good. Thanks for the clarification!.

**Comment by apollostream** [comment]
I am willing to contribute the R source code behind the RStudio Shiny app I developed specifically for this purpose.  See the app here: ["Best Colleges for You"](https://thompsonml.shinyapps.io/BestCollegeApp/).  How should I go about contributing?

**Comment by barkimedes** [comment]
FYI, I'm planning to close this issue on September 1, 2022. I haven't worked on this project in 6 years and I can't find a different way to get this issue off of my open issues list. If you still need the issue, I'd suggest someone who still works on College Scorecard opening a new issue and referencing this one.

@alexsmithRTI -- tagging you because you're the person I see has committed to this repo recently and I suspect you'll know if this would cause any problem.

Thanks!
