### ISSUE TITLE
As a new site admin, I would like to not have to deal with ELK instances that are no longer in use

### ISSUE THREAD

**Issue by yozlet** [RTICWDT/college-scorecard#1457]
Clean up Ed-specific ELK resources

Now that we have logs.cloud.gov we don't need our own ELK instances for looking at logs any more. Currently there are proxies scattered among the various `ed` spaces with names like `elk-proxy` and `elk-kibana-proxy`, which can now go away. However, we should also make sure that **if** these proxies are connected to one or more ELK instances which are **solely dedicated** to dealing with CS logs, then these instances should also be cleaned up.

@sharms - is this something you can investigate?

**Comment by brownpl** [comment]
Looks like these were cleaned up. :tada:
