### ISSUE TITLE
Update documentation to reflect service info

### ISSUE THREAD

**Issue by abisker** [RTICWDT/college-scorecard#1478]
@sharms & @yozlet this is a ticket to ensure we update the Scorecard documentation to reflect the proper naming of the service (so that when the app re-starts it can find the service). 

Result from issue #1473

**Comment by abisker** [comment]
@sharms @yozlet any updates or notes we should put here before I move it to backlog for work pause?

**Comment by yozlet** [comment]
Not from me!

**Comment by brownpl** [comment]
Service names are now organized.
