### ISSUE TITLE
When I search for the site, I shouldn't see error text for /schools page

### ISSUE THREAD

**Issue by ultrasaurus** [RTICWDT/college-scorecard#1479]
Not sure how this got indexed.  Would be simple to fix with a re-direct:

![image](https://cloud.githubusercontent.com/assets/41906/12928285/651ce4b2-cf21-11e5-925c-dda9127d1613.png)

**Comment by dnesting** [comment]
Possibly Javascript could add a meta element with "noindex" for the no-ID case.  I believe Google would respect that, but I'm not positive.

**Comment by brownpl** [comment]
Huzzah! Looks like this one was resolved along the way. 

<img width="641" alt="screen shot 2016-10-17 at 1 10 26 pm" src="https://cloud.githubusercontent.com/assets/1619550/19453677/1d60c7fa-946b-11e6-94e6-a2e935956658.png">
