### ISSUE TITLE
Create documentation for Cloud.gov dependencies

### ISSUE THREAD

**Issue by ultrasaurus** [RTICWDT/college-scorecard#1484]
We need to understand which things are custom parts of the ED deployment and what things are "owned" by Cloud.gov, and document those things so new ED team will know what they are responsible for and what should be escalated by Cloud.gov

**Comment by abisker** [comment]
@ultrasaurus Any updates we should add to this one before moving to the backlog for work pause?

**Comment by brownpl** [comment]
Closing this, as I think these were all sorted out during the transition.
