### ISSUE TITLE
Set up SMS and dev-on-call shift rotation with PagerDuty

### ISSUE THREAD

**Issue by yozlet** [RTICWDT/college-scorecard#1490]
(Quoting from #1460:)

PagerDuty would give us SMS notification (which is more reliable than the NR mobile app) but, more importantly, would allow us much better routing and scheduling capabilities. We aren't the only ones who want PagerDuty; Bret has started pushing on acquiring service for Cloud.gov and the rest of 18F. NR can plug directly into PagerDuty once we get it.

**Comment by brownpl** [comment]
No longer relevant post transition.
