### ISSUE TITLE
As the Department of Education, we need a long-term, consistent mechanism to easily update the data so that we can do data drops.

### ISSUE THREAD

**Issue by barkimedes** [RTICWDT/college-scorecard#1494]
We need to provide the department of education a mechanism by which they can update the data. Ideally, it would be super duper sweet if they could update the data without engineering involvement. 

I know, I know, but one can dream :smiling_imp:

**Comment by saintsoup52** [comment]
If it is helpful... VA DS is developing a tool for VA to update the GI Bill Comparison tool without engineering involvement. 

We currently have over 10 different sources of data that get updated at different time... so the same issues you have... we have.

Maybe we should coordinate.

**Comment by barkimedes** [comment]
FYI, I'm planning to close this issue on September 1, 2022. I haven't worked on this project in 6 years and I can't find a different way to get this issue off of my open issues list. If you still need the issue, I'd suggest someone who still works on College Scorecard opening a new issue and referencing this one.

@alexsmithRTI -- tagging you because you're the person I see has committed to this repo recently and I suspect you'll know if this would cause any problem.

Thanks!
