### ISSUE TITLE
Bug: Threshold earnings show as 0% when privacy-suppressed

### ISSUE THREAD

**Issue by claremccann** [RTICWDT/college-scorecard#1499]
Example: Beacon College has privacy-suppressed earnings, but rather than showing as "data not available" (as with median earnings), it shows as "0%". Needs to reflect that the data aren't actually zero, they're missing. 

https://collegescorecard.ed.gov/school/?384254-Beacon-College

**Comment by barkimedes** [comment]
Dependent on issue #903

**Comment by kynetiv** [comment]
This was fixed from the API side of things, implemented in the [1.4.0](https://github.com/RTICWDT/open-data-maker/releases/tag/1.4.0) release.
