### ISSUE TITLE
BUG: Checkboxes are not visible under Advanced Search

### ISSUE THREAD

**Issue by LisaGee** [RTICWDT/college-scorecard#1524]
Mac, Safari
Steps to Repro:
1. Go to: https://collegescorecard.ed.gov/search/?name=phoenix&sort=advantage:desc
2. Under Edit Search, open Advanced Search.
3. See Public, For Profit and Non Profit words, but no checkboxes. See attached screenshot.

Expected Results:
Should see checkboxes

![image](https://cloud.githubusercontent.com/assets/12847090/13674785/e36b3876-e6ac-11e5-8b56-68b92e3930c7.png)

**Comment by NoahKunin** [comment]
@LisaGee Just passing while doing other research, but can't replicate either on Macbook / Safari 9.0.3 using default zoom settings. However, I *can* replicate if I "Zoom Out" via the browser.

Can you set View > Actual Size to see if it resolves, in order to confirm the origin? Thanks!

**Comment by brownpl** [comment]
Along the way as part of the transition, we also encountered this and traced it out to an issue with a border width, oddly enough. An adjustment has been made and seems to have resolved the issue.
