### ISSUE TITLE
BUG: college specific page loses 100% width upon clicking “View More Details”

### ISSUE THREAD

**Issue by nguyenist** [RTICWDT/college-scorecard#1525]
On any search result (only tested via iPhone 6S Plus)

Tap “View More Details”

**What happens:**
Page doesn’t span 100% of the width of the screen anymore.

**Expected action:**
Should fill 100% of page.

Wondering if this happens on smaller phones (non-phablets) as well. 
![image](https://cloud.githubusercontent.com/assets/4484141/13675141/3d4fb190-e6ae-11e5-8489-d048f40fc67c.png)

**Comment by kynetiv** [comment]
Implemented in #1551.
