### ISSUE TITLE
API link may be broken

### ISSUE THREAD

**Issue by claremccann** [RTICWDT/college-scorecard#1528]
Developers trying to use the API say the link may be broken. Http://api.data.gov/ed/collegescorecard/v1/schools and http://api.data.gov/ed/collegescorecard

**Comment by saintsoup52** [comment]
It is working for CFPB.... We just did a couple of pings.

**Comment by LisaGee** [comment]
It's working for College Scorecard too and does seem to have gone down. Possibly user error?

**Comment by brownpl** [comment]
Seems like this might have been a one off issue. The API is resolving for me. https://api.data.gov/ed/collegescorecard/v1/schools is the correct link to access the API. http://api.data.gov/ed/collegescorecard/ (note the trailing slash) should take users to a page that lists a few example calls. Valid API keys are required for both URIs.
