### ISSUE TITLE
Individual Anonymized data

### ISSUE THREAD

**Issue by alexWhitworth** [RTICWDT/college-scorecard#1559]
Where does the individual-level anonymized data live? For obvious reasons, this would be more valuable to researchers than the summary data.

I don't see any access to it from the documentation: https://collegescorecard.ed.gov/data/documentation/

**Comment by kynetiv** [comment]
You may want to try asking on the Open Data Stack Exchange, http://opendata.stackexchange.com/questions/tagged/collegescorecard. Issues here are mostly related to the code base for the site, bugs, etc.

**Comment by alexWhitworth** [comment]
Will do, thanks.
