### ISSUE TITLE
SSL/TLS certificate displays as "Research Triangle Institute"

### ISSUE THREAD

**Issue by dnesting** [RTICWDT/college-scorecard#1575]
Web browsers show the site as belonging to "Research Triangle Institute" and not "US Department of Education" or similar.  Is this expected?  From the user's perspective I think this is confusing.

![image](https://cloud.githubusercontent.com/assets/7342162/19454541/863673a8-9487-11e6-8c30-7238da3abe83.png)

![image](https://cloud.githubusercontent.com/assets/7342162/19454613/dbf007dc-9487-11e6-8f50-2e91a2c1e39c.png)

**Comment by saintsoup52** [comment]
I just had this happen to me and it was a little unnerving... I think this should be fixed because no offense RTI does not sound like a government agency.

**Comment by brownpl** [comment]
With a recent migration this issue has been resolved. Thanks for the feedback.
