### ISSUE TITLE
Difference in Most Recent Data and Annual Files 

### ISSUE THREAD

**Issue by kbd32** [RTICWDT/college-scorecard#1597]
I'm confused about why certain values are included in the "most recent cohorts" file are listed as null in the annual files. For example, agege24 has valid values for most schools in the most recent cohorts csv, but not the annual files, as is a lot of the earnings data. The problem then is that the most recent cohorts file doesn't list a year for when the values are measured, and doesn't allow you to retrieve historical data for earlier years.

**Comment by sudharsanmit** [comment]
@kbd32 I see the Scorecard api returning data for years only upto 2014. Do you know if there is anywhere I can get data for further years? Also if you have time, pls checkout my College Analyzer app at https://twitter.com/ChebuRakshu

**Comment by brownpl** [comment]
@kbd32 - The “most recent data” file compiles data elements from across different years, depending on what is the most recent available data, which is why there is variance compared to the annual files.  While it is true that the “most recent data” file does not indicate the source year, you can find it by downloading the data dictionary and referencing the tab “most recent cohort map.”
 
You may be interested to check out our [stack exchange board](http://opendata.stackexchange.com/questions/tagged/collegescorecard) for additional questions related to the data, as this forum is more for issues related to the website itself.

**Comment by btskinner** [comment]
@brownpl Thanks for the response. I'm following this thread to see if I need to change something in how the [rscorecard](https://github.com/btskinner/rscorecard) package pulls from the API. 

Do the website and API pull from two different data locations? (I know the data files available for download are a little different from the API.) I visited the linked stack exchange board, but that doesn't seem quite the right place for this question.

**Comment by brownpl** [comment]
@btskinner The data on the College Scorecard website is pulled from the API. Though the downloadable data files are separate from the API, the API data is actually generated from those files, so they should be in sync. We update the downloadable data files whenever we post a new version of the API. You can keep an eye on our [change log](https://collegescorecard.ed.gov/data/changelog/) for when things are updated.

**Comment by btskinner** [comment]
Thanks, @brownpl. To be clear on @kbd32's question: using the API, it's not currently possible to get historical values for some covariates (such as earnings data). To get those, one must download and use the full data files. Is that correct?

**Comment by sudharsanmit** [comment]
Hi Patrick. The API has only data up to 2013-14 whereas the downloadable
csv file has data up to 2014-15. The APi data is old.

On Tuesday, February 28, 2017, Patrick Brown <notifications@github.com>
wrote:
> @btskinner The data on the College Scorecard website is pulled from the
API. Though the downloadable data files are separate from the API, the API
data is actually generated from those files, so they should be in sync. We
update the downloadable data files whenever we post a new version of the
API. You can keep an eye on our change log for when things are updated.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/t0fzE2X8s6EwfC6WhULSABU_M3JQ93gr1WCfo0BPej8lTGideUoTNTV8pTrVIlE2ffkI256hSHxGlbdRY-a6ZRGFfPw6ciMeZ52ggX582uTs_PMguB1y6T5dktOJQGZdG0dj6I3OzBNZOj0raGNrbs-swImbEg=s0-d-e1-ft#https://github.com/notifications/beacon/AP-IYXX8-N5Agg3KmFKDQemP8vpdvJ3Cks5rhINQgaJpZM4MKVjL.gif>

**Comment by sudharsanmit** [comment]
One more thing -- all data points on the website reference hard coded 2014
fields. The earnings refer to 2012 field even when other data is pulled off
2014 fields. Why is there a discrepancy?

On Tuesday, February 28, 2017, Sudharsan R <sudharsan.mit@gmail.com> wrote:
> Hi Patrick. The API has only data up to 2013-14 whereas the downloadable
csv file has data up to 2014-15. The APi data is old.
>
> On Tuesday, February 28, 2017, Patrick Brown <notifications@github.com>
wrote:
>> @btskinner The data on the College Scorecard website is pulled from the
API. Though the downloadable data files are separate from the API, the API
data is actually generated from those files, so they should be in sync. We
update the downloadable data files whenever we post a new version of the
API. You can keep an eye on our change log for when things are updated.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/t0fzE2X8s6EwfC6WhULSABU_M3JQ93gr1WCfo0BPej8lTGideUoTNTV8pTrVIlE2ffkI256hSHxGlbdRY-a6ZRGFfPw6ciMeZ52ggX582uTs_PMguB1y6T5dktOJQGZdG0dj6I3OzBNZOj0raGNrbs-swImbEg=s0-d-e1-ft#https://github.com/notifications/beacon/AP-IYXX8-N5Agg3KmFKDQemP8vpdvJ3Cks5rhINQgaJpZM4MKVjL.gif>

**Comment by brownpl** [comment]
@btskinner Any data present in the file should be available in the API. That said, certain items do not appear in all files, for instance earnings data. You can reference the cohort map in the [Data Dictionary](https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx) for more information about what is available in each file. Hope that helps!

@sudharsanmit The data from the API that you reference with 2014 is from the 2014-15 school year. Is that the 2015 data you are referring to? As far as using 2012 earnings data in the Scorecard site, that is the most recent data that we have received from the Treasury department.

**Comment by btskinner** [comment]
@brownpl I think we're on the same page now. I use the Data Dictionary as the basis for my pseudo hash that converts variable names to developer friendly names (and vice versa). I did some more tests locally and it seems that data missing from the rscorecard API pull are also missing in the full data files. That is, the data are just missing for those institutions.

Let me ask this then: when a year is selected in an API call, is that akin to calling the **MERGED12<\*>_<\*>_PP.csv** file for that year? For example, adding `2014` to a call is like pulling that variable from the `MERGED2014_15_PP.csv`. Is that correct?

**Comment by sudharsanmit** [comment]
There is a serious flaw in data between Collegescorecard and NCES. I don't
believe collegescorecard which has launched only recently is correct.

All collegescorecard sources sources say the data is of 2014-15.

NPT45_PUB - 18023 (MERGED2014_15_PP)
https://collegescorecard.ed.gov/school/?230764-University-of-Utah
https://api.data.gov/ed/collegescorecard/v1/schools?id=230764&api_key=DEMO_KEY&fields=id,2014.cost.net_price.public.by_income_level.110001-plus


But, the IES-NCES [National Center for Education Statistics], I believe -
the authority of all Education data, says it is of 2013-14 and the 2014-15
figure for the same is $17,420.
Quite a serious flaw. Which is to be belived. They are off by a whole
academic year in every detail.

https://nces.ed.gov/collegenavigator/?id=230764

**Comment by brownpl** [comment]
@btskinner - Yes, that is correct. 

@sudharsanmit I will relay your question to the data team. Thanks.

**Comment by sudharsanmit** [comment]
Thanks @brownpl . I appreciate your help.

**Comment by btskinner** [comment]
@brownpl - Thanks for the clarification. That really helps me moving forward.

**Comment by brownpl** [comment]
@sudharsanmit I've heard back from the data team. Here is the response: 

> The data dictionary cohort map indicates the correct time frame and cohort for the Net Price data included in the Scorecard files: AcadYr 2013-14, reported in IPEDS DCY2014-15.
>  
> The last full data refresh (which would include updating the IPEDS metrics) for the College Scorecard data was the Sept. 2016 release.  At that time, the publicly available IPEDS data were from the 2014-15 collection year, which is why the data files etc. are labeled with 2014_15. Since that time, IPEDS has publicly released data from the 2015-16 collection year, and these are the data on College Navigator; i.e., the College Navigator data is more recent than the College Scorecard data.

For further questions related to the data, you may want to try reaching out to [scorecarddata@rti.org](mailto:scorecarddata@rti.org) - the folks monitoring that email are much more familiar with the in and outs of the data than I am.

**Comment by sudharsanmit** [comment]
Thanks Patrick for your help :)

On Friday, March 3, 2017, Patrick Brown <notifications@github.com> wrote:
> @sudharsanmit I've heard back from the data team. Here is the response:
>
> The data dictionary cohort map indicates the correct time frame and
cohort for the Net Price data included in the Scorecard files: AcadYr
2013-14, reported in IPEDS DCY2014-15.
>
> The last full data refresh (which would include updating the IPEDS
metrics) for the College Scorecard data was the Sept. 2016 release. At that
time, the publicly available IPEDS data were from the 2014-15 collection
year, which is why the data files etc. are labeled with 2014_15. Since that
time, IPEDS has publicly released data from the 2015-16 collection year,
and these are the data on College Navigator; i.e., the College Navigator
data is more recent than the College Scorecard data.
>
> For further questions related to the data, you may want to try reaching
out to scorecarddata@rti.org - the folks monitoring that email are much
more familiar with the in and outs of the data than I am.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/1LbnZ4kbAtV5l-vtJGBtdaIHjD5c19m3jJal5uLLTpZRLUN-u-A7N8wKMaxiK9cLkN-FEh5jvsyctq6dvwUpMQF0faPgo_X4_-TbahJCMTTF-nvvto--HnhHjB3jzevPA6whLNnLVDz_4A5QmNdgSu9SVoND1w=s0-d-e1-ft#https://github.com/notifications/beacon/AP-IYS1ethpeHuf0s5eAB9guruKyIVFrks5riE5pgaJpZM4MKVjL.gif>

**Comment by brownpl** [comment]
Seems like we have happy campers here. 
As always, thank you for the feedback/input!
