### ISSUE TITLE
GI Bill is a registered trademark and needs a "®"

### ISSUE THREAD

**Issue by saintsoup52** [RTICWDT/college-scorecard#1606]
College Scorecard should being following the VA terms of use when they post "GI Bill" on the College Scorecard. 

http://benefits.va.gov/GIBILL/Trademark_Terms_of_Use.asp

In the following link there should be a registered trademark symbol "®"

![image](https://cloud.githubusercontent.com/assets/4397508/24957942/9c7828fa-1f5b-11e7-9eee-1aa6801d4ba0.png)

**Comment by brownpl** [comment]
Thanks! I've prepared #1607 to resolve this issue. It should go up with our next batch of changes.

**Comment by saintsoup52** [comment]
Thank you!
