### ISSUE TITLE
Checking on variable -relaffil- 

### ISSUE THREAD

**Issue by adamrossnelson** [RTICWDT/college-scorecard#1653]
I was checking on variable -relaffil- in the latest updated data from September 2017. The previous January version had religious affiliation but it looks that the Sep 2017 data has all NULL values.

**Comment by brownpl** [comment]
The values for religious affiliation can be found in the most recent data file, so after this recent release, they will now be available in MERGED2015_16_PP.csv provided you are using the raw data files. If you are using the API, they should also be available in the school object.

**Comment by adamrossnelson** [comment]
Got it. Thanks.
