### ISSUE TITLE
All APIs returning HTTP 503 error

### ISSUE THREAD

**Issue by karankalra** [RTICWDT/college-scorecard#1662]
The website also seems to be down

**Comment by brownpl** [comment]
Our platform provider is experiencing technical difficulties. They are currently working to resolve connectivity. You can monitor https://cloudgov.statuspage.io/ for the latest updates and I will update this issue when things are back up and running. Thank you for your patience.

**Comment by brownpl** [comment]
The cloud.gov team has worked to resolve the issues they were having and the website and API are now back online and are operating as expected. Let us know if you continue to experience issues and we will look into them.

**Comment by karankalra** [comment]
Thanks for the prompt reply, Patrick. I really appreciate it.
