### ISSUE TITLE
No data.yaml present in CollegeScore_raw_data

### ISSUE THREAD

**Issue by ashjambhulkar** [RTICWDT/college-scorecard#1663]
data.yaml file is not present in full data set, it contains only csv files.

**Comment by brownpl** [comment]
Thanks for the feedback. I am attaching the data.yaml here and we will look into the feasibility of including that in zip downloads going forward. This information can also be found in json format at this endpoint: https://api.data.gov/ed/collegescorecard/v1/data.json?api_key={KEY}

[data.yaml.zip](https://github.com/RTICWDT/college-scorecard/files/1759942/data.yaml.zip)

**Comment by kynetiv** [comment]
Thanks, the current `Download All Data` zip  now contains the most recent data.yaml. Found [here](https://collegescorecard.ed.gov/data/).
