### ISSUE TITLE
Recognize zip codes from Puerto Rico

### ISSUE THREAD

**Issue by froi** [RTICWDT/college-scorecard#1680]
**Expected Behaviour**

The website should be able to recognize zip codes from Puerto Rico, the US Virgin Islands, and other territories.

**Current Behaviour**

While using the website I entered the zip code 00907 and it was flagged as not valid:

![image](https://user-images.githubusercontent.com/1918027/42537164-1c2429d4-8462-11e8-9419-29c3048ce6f5.png)

Using https://usps.com I get:

![image](https://user-images.githubusercontent.com/1918027/42537334-96741a82-8462-11e8-9f5a-aeb68cd69776.png)

The same thing happened for the US Virgin Islands 

![image](https://user-images.githubusercontent.com/1918027/42537529-2176a74e-8463-11e8-9d47-0ded78994c16.png)

![image](https://user-images.githubusercontent.com/1918027/42537547-333361e8-8463-11e8-97be-a61ae228f5f4.png)

**Possible solution**

Use the USPS [Web Tools APIs](https://www.usps.com/business/web-tools-apis/welcome.htm) to validate zip codes.

**Comment by kynetiv** [comment]
Hi, thanks for filing the issue! We've updated the API's zip codes dataset to include Puerto Rico, U.S. Virgin Islands and other regions.

**Comment by froi** [comment]
I'm a bit late with this but thank you for all your work @kynetiv
