### ISSUE TITLE
Data dictionary doesn't include dev friendly names for new fields of study variables

### ISSUE THREAD

**Issue by btskinner** [RTICWDT/college-scorecard#1733]
Downloading the [data dictionary from the site](https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx), the new tab in the spreadsheet, `FieldOfStudy_data_dictionary` doesn't include any values for `dev-category` or `developer-friendly name`. 

Looking at `data.yml` in full download of files (`CollegeScorecard_Raw_Data`), it seems like the category is `programs` and that dev friendly names exist. I use the data dictionary to update the [{rscorecard}](https://cran.r-project.org/package=rscorecard) R package. Is the data dictionary to be updated, too?

**Comment by brownpl** [comment]
Thanks for filing this issue - I had made an adjustment and uploaded the incorrect file. I just pushed up a new one that should have the developer-friendly names populated for you.

**Comment by btskinner** [comment]
Got it and all looks good. Thanks!

**Comment by btskinner** [comment]
Hi, reopening b/c it seems that the 12/12 update dropped the values for `dev-category` and `developer friendly name` columns in the `FieldOfStudy_data_dictionary` sheet. I can use the old sheet for now, but having the updated one available for download again would be helpful. Thanks.

**Comment by brownpl** [comment]
Ah! Thanks. We just pushed an update to resolve this and I think all the powers that be now have the accurate version to edit going forward.

**Comment by btskinner** [comment]
Works again. Thanks as always!
