### ISSUE TITLE
Access programs data by API

### ISSUE THREAD

**Issue by gopala000** [RTICWDT/college-scorecard#1766]
I have a need to query programs data by API. When I tried below sample call, I get an error message

{
    "error": 404,
    "message": "programs not found. Available endpoints: schools"
}

Is programs endpoint available in a later version? If it is available, please share the version number to use.

Thanks.

Sample call: 
```
https://api.data.gov/ed/collegescorecard/v1/programs.json?programs.cip_4_digit.code=11.07&cip_4_digit.credential.level
=2,3&fields=cip_4_digit.id
,cip_4_digit.school.name
cip_4_digit.code
,cip_4_digit.title
cip_4_digit.earnings.median_earnings,cip_4_digit.debt.median_debt&sort=cip_4_digit.earnings.median_earnings:desc&api_key=<APIKEYREMOVED>
```

**Comment by JAFrederick** [comment]
Hello,
The program data is currently nested within institution level data and available at the `schools` endpoint.

Adjusted API call:
```
https://api.data.gov/ed/collegescorecard/v1/schools?api_key=API_KEY_HERE&
latest.programs.cip_4_digit.code=1107&
latest.programs.cip_4_digit.credential.level=2,3&
fields=latest.programs.cip_4_digit.unit_id,latest.programs.cip_4_digit.school.name,latest.programs.cip_4_digit.code,latest.programs.cip_4_digit.title,latest.programs.cip_4_digit.earnings.median_earnings,latest.programs.cip_4_digit.debt.median_debt&
sort=latest.programs.cip_4_digit.earnings.median_earnings:desc
```

Some quick notes on the adjusted call:
- Alter endpoint from `programs` to `schools`
- Alter `programs.cip_4_digit.code=11.07` to `latest.programs.cip_4_digit.code=1107`
- Alter `cip_4_digit.credential.level=2,3` to `latest.programs.cip_4_digit.credential.level=2,3`
- Alter `fields=*` to 
```
fields=
latest.programs.cip_4_digit.unit_id,
latest.programs.cip_4_digit.school.name,
latest.programs.cip_4_digit.code,
latest.programs.cip_4_digit.title,
latest.programs.cip_4_digit.earnings.median_earnings,
latest.programs.cip_4_digit.debt.median_debt
```
- Alter `sort=cip_4_digit.earnings.median_earnings:desc` to `sort=latest.programs.cip_4_digit.earnings.median_earnings:desc`.  

**Please Note:** Sorting of program level data is not currently functioning as intended.  We are in the process of addressing this issue.

**Comment by Paradoxinit** [comment]
I am trying to query the API by programs title, but returns empty error. Now If just set the field to show the titles only and remove the search field, it shows me all the program titles.
The url I am using: https://api.data.gov/ed/collegescorecard/v1/schools?api_key={API_KEY}&fields=id,school.name,latest.programs.cip_4_digit.title&latest.programs.cip_4_digit.credential.level=3&latest.programs.cip_4_digit.title=Computer+Science
Does the API support searching by program titles?
