### ISSUE TITLE
Architecture Field of Study Search showing 0 results

### ISSUE THREAD

**Issue by jabba08** [RTICWDT/college-scorecard#1810]
There is some issue with certain field of study searches. For example, searching for architecture yields 0 results. There are many other examples.

![image](https://user-images.githubusercontent.com/26335521/88500591-b78d0700-cf8e-11ea-8cff-a809d976fe4c.png)

**Comment by JAFrederick** [comment]
Thank you for reporting this issue.  This is happening at the API level.  We are currently processing a fix for this issue.  I will be sure to updated this ticket when the fix is live.

**Comment by JAFrederick** [comment]
This issue has been resolved at the API level.  The data store was missing leading zeros for some Fields Of Study (Academic Fields).
