### ISSUE TITLE
Rate Limiting Clarification?

### ISSUE THREAD

**Issue by rbadi2020** [RTICWDT/college-scorecard#1817]
Hello,

Can the team clarify in terms of any rate limiting with respect to using this api: https://api.data.gov/ed/collegescorecard/v1/schools.json?

Observing this in the headers:

X-RateLimit-Limit →1000
X-RateLimit-Remaining →998

Is the X-RateLimit-Limit above per hour or per day? Please clarify and confirm.

**Comment by JAFrederick** [comment]
Issue resolved in Open Data Maker repo: https://github.com/RTICWDT/open-data-maker/issues/102

Closing for now, Feel free to open again if the issue has not been resolved.
