### ISSUE TITLE
Bug: Netprice incorrectly appearing as $0 on family income chart

### ISSUE THREAD

**Issue by saintsoup52** [RTICWDT/college-scorecard#713]
Search "Oxnard College" and open the costs drawer.  The net price for family income shows up as "$0" for all the incomes above $30,000.

![image](https://cloud.githubusercontent.com/assets/4397508/9516615/c8701c6e-4c77-11e5-95f3-2a47dff2557b.png)

The expected result should be values greater then zero and higher then the lowest income bracket

![image](https://cloud.githubusercontent.com/assets/4397508/9516618/d771bcf4-4c77-11e5-87c7-86fad3a2ffea.png)

**Comment by LisaGee** [comment]
@jjoteal Great example of an edge case needed for Data Not Available. In this case, our data only has a value for the first income bracket. The other 4 are NULL.

**Comment by LisaGee** [comment]
Also mailed Clare to see why another site has data, but ours shows NULL. Different data source?

**Comment by LisaGee** [comment]
Making this a data only issue.
Look at #528 for display issue.
