### ISSUE TITLE
School Basics / Size: Small, Medium, Large

### ISSUE THREAD

**Issue by schakj** [RTICWDT/college-scorecard#789]
2000 is kind of a low cut-off for small schools.  I would suggest raising it to 3000 or 4000.

**Comment by LisaGee** [comment]
@jjoteal I presume you got the size definitions from someplace else and wanted to use them for consistency?

**Comment by jjoteal** [comment]
@LisaGee I'm not sure what the cut-offs are in the data, but assuming they are the same as what displays in College Navigator, these are the definitions:

![image](https://cloud.githubusercontent.com/assets/12192706/9579754/e10f2c80-4fc2-11e5-9ad8-39e9d2eef9fe.png)

**Comment by barkimedes** [comment]
@LisaGee Are we happy with the cutoffs as they are? If so, can we close this?
