### ISSUE TITLE
BUG: Earnings / Salary 10 Years After / Above, at, below average

### ISSUE THREAD

**Issue by schakj** [RTICWDT/college-scorecard#814]
Includes above average, but this item should not appear - per policy decision.

**Comment by LisaGee** [comment]
@schakj Can you provide more info via email to me and Clare? Not sure I'm following. Thanks.

**Comment by barkimedes** [comment]
@schakj This sounds similar to #858. Is it the same underlying issue (that we shouldn't be displaying the text 'above/below average')?
