### ISSUE TITLE
Potential Enhancement:  After landing on the results page, allow the option to search again without going back to the home page

### ISSUE THREAD

**Issue by sullivanse** [RTICWDT/college-scorecard#829]
I'm using Google Chrome.  5:26pm.  At this link: https://college-choice.18f.gov/search/?name=Boston%20University&sort=advantage:desc

Potential enhancement:  After landing on the results page, allow the user to do another search from the results page--rather than having to go back to the homepage.

Due to the known bug where the search field is case sensitive, I kept getting zero results when I searched things like "boston university."  Because I didn't know about the bug, I kept wanting to do new searches, and I wanted to conduct the search from the results page, but I had to go back to the homepage.

![image](https://cloud.githubusercontent.com/assets/9384522/9557469/3f44ed5a-4daa-11e5-84db-a7e5eae785c5.png)

**Comment by LisaGee** [comment]
Ruh-oh - @sullivanse I guess you didn't see the Filter and edit your search element towards the top of the page? Or do you mean something different? p.s. Have filed a ticket to make the type bigger to the element is more noticeable.

**Comment by barkimedes** [comment]
@sullivanse The filtering and search edit fields are much more prevalent now. Would you consider this issue resolved (and closeable :wink: )? Or is there more you think that should be done?

**Comment by brownpl** [comment]
The Edit Search is now more prominent since the screenshot provided.
