### ISSUE TITLE
BUG:  "Share this school" link is not working

### ISSUE THREAD

**Issue by sullivanse** [RTICWDT/college-scorecard#871]
I'm using IE 11.  Accessing this link at 6:20pm:  https://college-choice.18f.gov/school/?164988-Boston-University

When I click "Share this link" nothing happens.

![image](https://cloud.githubusercontent.com/assets/9384522/9558260/82524096-4db1-11e5-9703-2289b97a29ac.png)

**Comment by brownpl** [comment]
This link appears to be working fine. Perhaps a mail application was not available.
