### ISSUE TITLE
Snapshot/Rollback of elasticsearch index and data.yaml

### ISSUE THREAD

**Issue by hollyallen** [RTICWDT/college-scorecard#936]
During software deployments, need a way to snapshot and rollback volatile data. I believe this is limited to the elasticsearch data.

**Comment by ultrasaurus** [comment]
updated subject to be explicit.  In addition to elasticsearch index, the data.yaml is also important to snapshot.

I'm working with @ozzyjohnson on this.

**Comment by ultrasaurus** [comment]
scripts complete and tested with all 18 years of data, which takes about 7 hours to index, and about 6 minutes to restore

https://github.com/18F/college-choice-data/pull/4

-> @yozlet to review & accept if it looks good.

**Comment by ultrasaurus** [comment]
this apparently only fails for me, but we need to debug so I can do this too.  Prolly need more error handling in the script...
```
./snap.rb production create
cf target -s production
                   
API endpoint:   https://api.cloud.gov (API version: 2.44.0)   
User:           sarah.allen@gsa.gov   
Org:            ed   
Space:          production   
local data.yaml saved: /Users/sarahallen/src/18F/open-data-maker/real-data/ed-college-choice-production.yaml
copying from: /Users/sarahallen/src/18F/open-data-maker/real-data/ed-college-choice-production.yaml
saved in bucket: ed-college-choice-backup as: production-2016-01-19-1509.yaml
creating snapshot index-production-2016-01-19-1509
./cf-service-proxy/es-util.sh -c backup -s bservice -p $(./cf-service-proxy/make-proxy.sh -s eservice -up) -n index-production-2016-01-19-1509
Looking for jq.
  - Found jq.
Getting bindings for bservice.
Attempting to create repo backup using service proxy https://es:ujob0hxardhgcear@ed-production-eservice-proxy.18f.gov
  - result: {"acknowledged":true}
Attempting to create snap index-production-2016-01-19-1509.
  - result: {"accepted":true}
parse error: Invalid numeric literal at line 1, column 7
  - backup status: 
parse error: Invalid numeric literal at line 1, column 7
  - backup status: 
parse error: Invalid numeric literal at line 1, column 7
```

**Comment by ultrasaurus** [comment]
progress: https://github.com/18F/college-choice-data/pull/13 and  https://github.com/18F/cf-service-proxy/pull/13

**Comment by ultrasaurus** [comment]
Depending on how fast we get the indexing (https://github.com/18F/college-choice/issues/1081), we might want to revisit this approach

**Comment by abisker** [comment]
@ultrasaurus good to close out?

**Comment by brownpl** [comment]
Snap.rb does allow rollbacks now.
