### ISSUE TITLE
BUG: Searching for my zip code (20009) returns no results

### ISSUE THREAD

**Issue by kimballce** [RTICWDT/college-scorecard#979]
Edge browser, windows 10.
I did not add a radius.

**Comment by LisaGee** [comment]
@kimballce Are there any schools in your zip code? When I enter my home zip code 10023 I do get a result, b/c there is a school within my zip.

**Comment by kimballce** [comment]
@LisaGee , No there aren't any schools in my zip code. But I have been conditioned by most other websites on the internet to expect that entering my zip code will find results "near me", not just those exactly within my zip code. (e.g. https://order.pizzahut.com/site/locator)

I would recommend that if a user searches by zip code but leaves the radius field blank, that the default behavior should be to assume a 25 (or 10?) mile radius

**Comment by LisaGee** [comment]
I like this idea. Rather than have blank Miles radius. Have a default of 10 miles.

**Comment by barkimedes** [comment]
Jamie Isaac (isaac@rti.org) also reported a user who entered Colorado as the state and 80915 as the zip with no mile radius specified. Only got one result even though there are 12 schools in Colorado Springs. So we may want to follow up once this is updated.

**Comment by barkimedes** [comment]
Also look at #1250 if you work on this issue

**Comment by abisker** [comment]
@barkimedes is it fair here to change the story to center on having a default 10 mi radius to achieve the 'near me' feature?

**Comment by LisaGee** [comment]
I think the best way to solve for this is to have "10" appear as the default text in the Miles box, so users can see what is being searched for.

**Comment by kynetiv** [comment]
Fixed in #1551.
